server:
  port: 10086
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-jdbc?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root

logging:
  level:
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
  config: classpath:logback-spring.xml


